### ISSUE TITLE
[APP-MM] Module Manager [Service] - Available Modules

### ISSUE THREAD

**Issue by GundlackFelixDEV** [healthhackersER/CAMA-CORE-Example#3]
# ToDo
Add a service providing a list of  available Modules

# Description
Context provides a way to pass data through the component tree without having to pass props down manually at every level.

> [Context](https://reactjs.org/docs/context.html) provides a way to share values like these between components without having to explicitly pass a prop through every level of the tree.
>
> In a typical React application, data is passed top-down (parent to child) via props, but this can be cumbersome for certain types of props (e.g. locale preference, UI theme) that are required by many components within an application. 

# Requirements
- [ ] Module Model
- [ ] Module Manager [Service]
- [ ] Module Scree [Screen]
   - [ ] Module List [Component]
   - [ ] Module ListItem [Component]

# Implementations / Remarks
- [Article: The Unstaded React Service Pattern](https://hmh.engineering/the-unstated-react-service-pattern-786ea6168d1d
https://hmh.engineering/the-unstated-react-service-pattern-786ea6168d1d)
- [Doc](https://reactjs.org/docs/context.html)
- [HowTo: Use the new React context API](https://hackernoon.com/how-to-use-the-new-react-context-api-fce011e7d87)
- [ HowTo: Working with the React Context API](https://www.toptal.com/react/react-context-api)
